# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue here! Please follow the issue template to help us help you ğŸ‘ğŸ‰ğŸ˜„
  If you have screenshots to share demonstrating the issue, that's really helpful! ğŸ“¸

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸ 
 Your code will likely be published to code.publiclab.org in the next few days. 
 In the meantime, can you tell us your Twitter handle so we can thank you properly?
 Now that you've completed this, you can help someone else take their first step! See: https://code.publiclab.org

# It is recommend to include as many gifs and emojis as possible
  
